FROM openjdk:17-alpine

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 8080

ARG AUTH
ARG IV

RUN echo "auth=${AUTH}"
RUN echo "iv=${IV}"

COPY ./join/build/libs/join-0.0.1-SNAPSHOT.jar deploy.jar
RUN echo "java -jar deploy.jar --auth=$AUTH --iv=$IV" > run.sh && chmod +x run.sh
CMD ["sh", "run.sh"]
